# Generated by Django 5.2.8 on 2026-01-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_ingredient_restaurant_recipe_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
