# Generated by Django 5.2.8 on 2026-02-15 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_alter_shift_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="restaurants.restaurant"
            ),
        ),
    ]
